name: Testcheck
on:
  issue_comment:
    types: [created]

jobs:
  squash:
    runs-on: ubuntu-latest
    steps:
      - name: Check comment body
        if: github.event.comment.body == 'check'
        run: |
          pr=$(curl -X GET ${{ github.event.issue.pull_request.url }} -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}')
          sha=$(echo $pr | jq -r '.head.sha')
          curl -X POST https://api.github.com/repos/${{ github.repository }}/check-runs -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' 'Accept: application/vnd.github.antiope-preview+json' --data \
            '{ "name": "squash", "head_sha": "$(sha)", "status": "in_progress", "output": { "title": "Squash", "summary": "combine all commits in this PR into one", "text": "" } }'
