name: Squash
on:
  check_run:
    types: [created]

jobs:
  squash:
    runs-on: ubuntu-latest
    steps:
      - name: Check comment body
        run: |
          echo "oke bro ${{ github.event.check_run }}"